# Category.create(title: 'Movies')
# Category.create(title: 'Tools')
# Category.create(title: 'Home')
# Category.create(title: 'Clothes')
# Category.create(title: 'Technology')
# Category.create(title: 'Books')

# Item.create(name: 'Kung Fu Panda', description: 'movies', price: 15, category_id: 1 )
# Item.create(name: 'Snatch', description: 'movie', price: 20, category_id: 1)
# Item.create(name: 'Hammer', description: 'Thors hammer', price: 500000, category_id: 2)

User.create(name: "Josh Ullman", username: "josh", password: "password")
User.create(name: "Alex Cusack",  username:"alex", password:"password" )
User.create(name: "David Grotting", username:"david", password: "password" )
User.create(name: "Vivek Poola", username:"vivek", password: "password" )
User.create(name: "Arielle Chen",  username:"arielle", password: "password" )
User.create(name: "Le Tran", username:"le", password: "password" )
User.create(name: "Eric Saxman",  username:"eric", password: "password" )
User.create(name: "Carissa Blossom", username:"carissa", password: "password" )
User.create(name: "Ellis Marte",  username:"ellis", password: "password" )
User.create(name: "James Newman",  username:"james", password: "password" )
User.create(name: "Mike Farr",  username:"mike", password: "password" )
User.create(name: "Travis S",  username:"travis", password: "password" )
User.create(name: "Alex Kass",  username:"alex", password: "password" )
User.create(name: "Patrick Betti", username:"patrick", password: "password" )
User.create(name: "Jeff Chang",  username:"jeff", password: "password" )
User.create(name: "Andrew Donato", username:"andrew", password: "password" )
User.create(name: "Jennifer Jaochi", username:"jennifer", password: "password" )
User.create(name: "Ian Harris", username:"ian", password: "password" )
User.create(name: "Brian Kennedy", username:"brian", password: "password" )
User.create(name: "Benoit Demonsan", username:"benoit", password: "password" )
User.create(name: "Diana Lozano",  username:"diana", password: "password" )
User.create(name: "Eric Flores",  username:"eric", password: "password" )
User.create(name: "Henry Vega",  username:"henry", password: "password" )
User.create(name: "Karan Aditya",  username:"karan", password: "password" )
User.create(name: "Kelvin Gann",  username:"kelvin", password: "password" )
User.create(name: "Nicholas Toulou", username:"nick", password: "password" )
User.create(name: "Tanay Arora",  username:"tanay", password: "password" )
User.create(name: "Staunton Sample", username:"staunton", password: "password" )
User.create(name: "Erica Prenga",  username:"erica", password: "password" )
User.create(name: "Tom Tom",  username:"tom", password: "password" )
User.create(name: "Brick Thornton", username:"brick", password: "password" )
User.create(name: "Hunter Chapman", username:"hunter", password: "password" )
User.create(name: "Jared Grippe", username:"jared", password: "password" )